"""事件规则表 — 流年与命局互动 → 人事事件映射

一共六大类、41条核心规则。每条规则输出结构化事件，
供 EventTracer 使用，也可被 AI 润色为自然语言。

设计原则：
1. 规则是"原子事件"——一条规则描述一种互动类型 x 一个被影响对象
2. 一个年份可能触发多条规则 → 多原子事件合成完整描述
3. 置信度三维锚定：典籍支撑 × 0.5 + 因果直接性 × 0.3 + 互动强度 × 0.2
"""

from typing import Optional

# ============================================================
# 工具函数
# ============================================================

# 五行生克关系
WUXING_SHENG = {"木": "火", "火": "土", "土": "金", "金": "水", "水": "木"}
WUXING_KE = {"木": "土", "土": "水", "水": "火", "火": "金", "金": "木"}
WUXING_BEI_SHENG = {v: k for k, v in WUXING_SHENG.items()}  # 谁生我
WUXING_BEI_KE = {v: k for k, v in WUXING_KE.items()}        # 谁克我

CLASH_PAIRS = {
    "子": "午", "午": "子", "丑": "未", "未": "丑",
    "寅": "申", "申": "寅", "卯": "酉", "酉": "卯",
    "辰": "戌", "戌": "辰", "巳": "亥", "亥": "巳",
}

LIUHE_PAIRS = {
    "子": "丑", "丑": "子", "寅": "亥", "亥": "寅",
    "卯": "戌", "戌": "卯", "辰": "酉", "酉": "辰",
    "巳": "申", "申": "巳", "午": "未", "未": "午",
}

# 三刑
XING_SETS = [
    {"寅", "巳", "申"},  # 无恩之刑
    {"丑", "戌", "未"},  # 恃势之刑
    {"子", "卯"},        # 无礼之刑
]
HAI_PAIRS = {
    "子": "未", "未": "子", "丑": "午", "午": "丑",
    "寅": "巳", "巳": "寅", "卯": "辰", "辰": "卯",
    "申": "亥", "亥": "申", "酉": "戌", "戌": "酉",
}

# ============================================================
# 事件规则定义
# ============================================================

EVENT_RULES = {
    # ==========================================================
    # 类别 A：宫位互动（12条）
    # ==========================================================
    "A1_branch_clash_year": {
        "id": "A1",
        "category": "宫位互动",
        "interaction_type": "冲",
        "target_pillar": "年",
        "event_type": "家庭",
        "event_detail": "年柱受冲，祖上或父母长辈方面可能有变动、搬迁或健康问题",
        "base_confidence": 0.72,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.80,
        "classical_authority": 0.75,
    },
    "A2_branch_clash_month": {
        "id": "A2",
        "category": "宫位互动",
        "interaction_type": "冲",
        "target_pillar": "月",
        "event_type": "事业",
        "event_detail": "月柱事业宫受冲，工作环境或岗位可能有变动，父母方面也需留意",
        "base_confidence": 0.72,
        "classical_source": "《子平真诠》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.80,
        "classical_authority": 0.75,
    },
    "A3_branch_clash_day": {
        "id": "A3",
        "category": "宫位互动",
        "interaction_type": "冲",
        "target_pillar": "日",
        "event_type": "婚姻",
        "event_detail": "日支夫妻宫受冲，婚姻感情方面有较大波动或变动，单身者可能有感情变化",
        "base_confidence": 0.81,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.90,
        "classical_authority": 0.85,
    },
    "A4_branch_clash_hour": {
        "id": "A4",
        "category": "宫位互动",
        "interaction_type": "冲",
        "target_pillar": "时",
        "event_type": "子女",
        "event_detail": "时柱子女宫受冲，子女方面或下属关系可能有变动",
        "base_confidence": 0.68,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.80,
        "classical_authority": 0.65,
    },
    "A5_branch_he_year": {
        "id": "A5",
        "category": "宫位互动",
        "interaction_type": "合",
        "target_pillar": "年",
        "event_type": "家庭",
        "event_detail": "年柱被合，与祖上、长辈缘分增进，可能有家庭团聚或得到长辈帮助",
        "base_confidence": 0.63,
        "classical_source": "《子平真诠》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.70,
        "classical_authority": 0.65,
    },
    "A6_branch_he_month": {
        "id": "A6",
        "category": "宫位互动",
        "interaction_type": "合",
        "target_pillar": "月",
        "event_type": "事业",
        "event_detail": "月柱被合，事业上可能有合作机会，或工作环境有新的融合与调整",
        "base_confidence": 0.63,
        "classical_source": "《子平真诠》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.70,
        "classical_authority": 0.65,
    },
    "A7_branch_he_day": {
        "id": "A7",
        "category": "宫位互动",
        "interaction_type": "合",
        "target_pillar": "日",
        "event_type": "婚姻",
        "event_detail": "日支夫妻宫被合，有婚恋缘分或感情进展，已婚者需防外缘干扰",
        "base_confidence": 0.72,
        "classical_source": "《子平真诠》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.85,
        "classical_authority": 0.75,
    },
    "A8_branch_xing_early": {
        "id": "A8",
        "category": "宫位互动",
        "interaction_type": "刑",
        "target_pillar": "年/月",
        "event_type": "家庭/事业",
        "event_detail": "年月柱见刑，早运不顺，长辈或事业方面有纠缠、纠纷之事",
        "base_confidence": 0.50,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.60,
        "causality_directness": 0.55,
        "classical_authority": 0.50,
    },
    "A9_branch_xing_day": {
        "id": "A9",
        "category": "宫位互动",
        "interaction_type": "刑",
        "target_pillar": "日",
        "event_type": "婚姻",
        "event_detail": "夫妻宫见刑，婚姻中有摩擦或纠结之事，需注意沟通",
        "base_confidence": 0.50,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.60,
        "causality_directness": 0.65,
        "classical_authority": 0.45,
    },
    "A10_branch_hai_any": {
        "id": "A10",
        "category": "宫位互动",
        "interaction_type": "害",
        "target_pillar": "任意",
        "event_type": "综合",
        "event_detail": "宫位见害，对应人事有暗损、小人是非或隐蔽的不顺",
        "base_confidence": 0.40,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.40,
        "causality_directness": 0.40,
        "classical_authority": 0.40,
    },
    "A11_branch_zhilin_yue": {
        "id": "A11",
        "category": "宫位互动",
        "interaction_type": "值临（地支伏吟）",
        "target_pillar": "年/月",
        "event_type": "事业/家庭",
        "event_detail": "年月柱值临（地支伏吟），事业或家庭方面有反复之事，旧事重提或来回折腾",
        "base_confidence": 0.60,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.60,
        "classical_authority": 0.60,
    },
    "A12_branch_zhilin_day": {
        "id": "A12",
        "category": "宫位互动",
        "interaction_type": "值临（地支伏吟）",
        "target_pillar": "日",
        "event_type": "综合",
        "event_detail": "日柱值临（地支伏吟），自身有反复、停滞或旧事重现之感，诸事进展缓慢",
        "base_confidence": 0.63,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.75,
        "classical_authority": 0.60,
    },

    # ==========================================================
    # 类别 B：用神互动（5条）
    # ==========================================================
    "B1_sheng_yongshen": {
        "id": "B1",
        "category": "用神互动",
        "interaction_type": "生",
        "target": "用神",
        "event_type": "事业",
        "event_detail": "用神得生，格局力量增强，事业有进展或得到贵人相助，整体运势向好",
        "base_confidence": 0.70,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.70,
        "classical_authority": 0.75,
    },
    "B2_ke_yongshen": {
        "id": "B2",
        "category": "用神互动",
        "interaction_type": "克",
        "target": "用神",
        "event_type": "事业",
        "event_detail": "用神受克，事业方面遇到阻碍或打击，格局暂时受损，需谨慎应对",
        "base_confidence": 0.75,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.75,
        "classical_authority": 0.80,
    },
    "B3_he_yongshen": {
        "id": "B3",
        "category": "用神互动",
        "interaction_type": "合",
        "target": "用神",
        "event_type": "事业",
        "event_detail": "用神被合，格局暂时被牵制，事业上可能有外部羁绊或身不由己之感，但也可能是新的机缘",
        "base_confidence": 0.60,
        "classical_source": "《子平真诠·论用神》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.60,
        "classical_authority": 0.65,
    },
    "B4_chong_yongshen_root": {
        "id": "B4",
        "category": "用神互动",
        "interaction_type": "冲根",
        "target": "用神之根",
        "event_type": "事业",
        "event_detail": "用神之根被冲，根基动摇，可能有突发变故或事业根基受损",
        "base_confidence": 0.72,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.70,
        "classical_authority": 0.75,
    },
    "B5_is_yongshen_year": {
        "id": "B5",
        "category": "用神互动",
        "interaction_type": "值临",
        "target": "用神",
        "event_type": "综合",
        "event_detail": "用神到位，运势上扬，诸事较为顺利，是发展进取的好时机",
        "base_confidence": 0.78,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.80,
        "classical_authority": 0.80,
    },

    # ==========================================================
    # 类别 C：忌神互动（3条）
    # ==========================================================
    "C1_sheng_jishen": {
        "id": "C1",
        "category": "忌神互动",
        "interaction_type": "生",
        "target": "忌神",
        "event_type": "综合",
        "event_detail": "忌神得生，不利因素加强，运势压力增大，诸事需谨慎保守",
        "base_confidence": 0.67,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.65,
        "classical_authority": 0.70,
    },
    "C2_zhi_jishen": {
        "id": "C2",
        "category": "忌神互动",
        "interaction_type": "制",
        "target": "忌神",
        "event_type": "综合",
        "event_detail": "忌神被制，不利因素得以化解，困境中可出现转机，化险为夷",
        "base_confidence": 0.67,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.65,
        "classical_authority": 0.70,
    },
    "C3_is_jishen_year": {
        "id": "C3",
        "category": "忌神互动",
        "interaction_type": "值临",
        "target": "忌神",
        "event_type": "综合",
        "event_detail": "忌神当值，运势低迷，多有阻碍不顺，诸事需谨慎，避免冒进",
        "base_confidence": 0.74,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.75,
        "classical_authority": 0.75,
    },

    # ==========================================================
    # 类别 D：日主互动（4条）
    # ==========================================================
    "D1_tiankedichong_day": {
        "id": "D1",
        "category": "日主互动",
        "interaction_type": "天克地冲",
        "target": "日柱",
        "event_type": "综合",
        "event_detail": "流年天克地冲日柱，是人生重大转折或变故之年，各方面均需特别注意",
        "base_confidence": 0.90,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 1.0,
        "causality_directness": 0.90,
        "classical_authority": 0.90,
    },
    "D2_jishen_ke_shen": {
        "id": "D2",
        "category": "日主互动",
        "interaction_type": "克",
        "target": "日主",
        "event_type": "健康",
        "event_detail": "忌神克身，需注意身体健康或精神压力增大，避免过劳",
        "base_confidence": 0.67,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.70,
        "classical_authority": 0.70,
    },
    "D3_yongshen_fu_shen": {
        "id": "D3",
        "category": "日主互动",
        "interaction_type": "生",
        "target": "日主",
        "event_type": "综合",
        "event_detail": "得生扶之年，精力充沛，有贵人扶持或得到外界助力",
        "base_confidence": 0.63,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.65,
        "causality_directness": 0.70,
        "classical_authority": 0.60,
    },
    "D2_weak_ke_shen": {
        "id": "D2w",
        "category": "日主互动",
        "interaction_type": "克",
        "target": "日主",
        "event_type": "健康",
        "event_detail": "身弱逢克，健康压力增大，需特别注意身体和意外之灾，凡事保守为上",
        "base_confidence": 0.74,
        "classical_source": "《滴天髓·体用》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.75,
        "classical_authority": 0.80,
    },
    "D2_strong_zhi_heng": {
        "id": "D2s",
        "category": "日主互动",
        "interaction_type": "克（制衡）",
        "target": "日主",
        "event_type": "事业",
        "event_detail": "身强得克（官杀制衡），过剩之力得以约束，反为有利，有管理和约束之力",
        "base_confidence": 0.65,
        "classical_source": "《滴天髓·体用》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.70,
        "classical_authority": 0.70,
    },
    "D3_weak_fu_shen": {
        "id": "D3w",
        "category": "日主互动",
        "interaction_type": "生（扶身）",
        "target": "日主",
        "event_type": "综合",
        "event_detail": "身弱得生扶之年，精力充沛，有贵人扶持或得到外界助力，运势上升",
        "base_confidence": 0.72,
        "classical_source": "《滴天髓·体用》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.80,
        "classical_authority": 0.75,
    },
    "D3_strong_guo_sheng": {
        "id": "D3s",
        "category": "日主互动",
        "interaction_type": "生（过旺）",
        "target": "日主",
        "event_type": "综合",
        "event_detail": "身强逢生扶，过犹不及，精力过剩易生焦躁或冲动之事，宜保守守成",
        "base_confidence": 0.67,
        "classical_source": "《滴天髓·体用》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.75,
        "classical_authority": 0.70,
    },
    "D4_rizhu_rumu": {
        "id": "D4",
        "category": "日主互动",
        "interaction_type": "入墓",
        "target": "日主",
        "event_type": "健康",
        "event_detail": "日主入墓，精神状态低迷，健康方面需加强注意，诸事进展迟缓",
        "base_confidence": 0.58,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.65,
        "causality_directness": 0.60,
        "classical_authority": 0.55,
    },

    # ==========================================================
    # 类别 E：十神特殊互动（10条）
    # ==========================================================
    "E1_zhengguan_ke_shang": {
        "id": "E1",
        "category": "十神特殊",
        "interaction_type": "克",
        "target": "正官",
        "trigger": "被伤官克",
        "event_type": "事业",
        "event_detail": "正官被伤官所克，事业上有官非、降职或被排挤之象",
        "base_confidence": 0.78,
        "classical_source": "《子平真诠·论正官》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.80,
        "classical_authority": 0.85,
    },
    "E2_zhengguan_bei_he": {
        "id": "E2",
        "category": "十神特殊",
        "interaction_type": "合",
        "target": "正官",
        "trigger": "被合",
        "event_type": "事业",
        "event_detail": "官星被合，职位或身份可能有变动，也可能是被其他事务所牵制",
        "base_confidence": 0.67,
        "classical_source": "《子平真诠·论正官》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.70,
        "classical_authority": 0.70,
    },
    "E3_qisha_wuzhi": {
        "id": "E3",
        "category": "十神特殊",
        "interaction_type": "无制",
        "target": "七杀",
        "trigger": "无制攻身",
        "event_type": "健康/事业",
        "event_detail": "七杀无制攻身，压力巨大，有意外之灾或事业上的强硬打压",
        "base_confidence": 0.83,
        "classical_source": "《子平真诠·论七杀》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "E4_qisha_bei_zhi": {
        "id": "E4",
        "category": "十神特殊",
        "interaction_type": "制",
        "target": "七杀",
        "trigger": "被食神制",
        "event_type": "事业",
        "event_detail": "食神制杀，化压力为权力，挑战中脱颖而出，有升职或掌权之机",
        "base_confidence": 0.83,
        "classical_source": "《子平真诠·论七杀》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "E5_zhengcai_bei_duo": {
        "id": "E5",
        "category": "十神特殊",
        "interaction_type": "夺",
        "target": "正财",
        "trigger": "被比劫夺",
        "event_type": "财运",
        "event_detail": "比劫夺财，有破财、被分财或被竞争夺走利益之事",
        "base_confidence": 0.83,
        "classical_source": "《子平真诠·论财》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "E6_piancai_bei_he": {
        "id": "E6",
        "category": "十神特殊",
        "interaction_type": "合",
        "target": "偏财",
        "trigger": "被合",
        "event_type": "财运",
        "event_detail": "偏财被合，意外之财的机会或投资有变动，可能是获得也可能是错失",
        "base_confidence": 0.63,
        "classical_source": "《子平真诠·论财》",
        "strength_coefficient": 0.65,
        "causality_directness": 0.65,
        "classical_authority": 0.65,
    },
    "E7_zhengying_bei_po": {
        "id": "E7",
        "category": "十神特殊",
        "interaction_type": "破",
        "target": "正印",
        "trigger": "被财破",
        "event_type": "学业/家庭",
        "event_detail": "财星破印，学业或文书不利，母亲健康需留意",
        "base_confidence": 0.78,
        "classical_source": "《子平真诠·论印绶》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.80,
        "classical_authority": 0.80,
    },
    "E8_shishen_bei_duo": {
        "id": "E8",
        "category": "十神特殊",
        "interaction_type": "夺",
        "target": "食神",
        "trigger": "被偏印夺",
        "event_type": "才华/健康",
        "event_detail": "枭神夺食，才华发挥受阻，食禄有损，女命需注意子女方面，健康亦宜留意",
        "base_confidence": 0.78,
        "classical_source": "《子平真诠·论食神》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.80,
        "classical_authority": 0.80,
    },
    "E9_shangguan_jian_guan": {
        "id": "E9",
        "category": "十神特殊",
        "interaction_type": "见",
        "target": "伤官",
        "trigger": "见正官",
        "event_type": "事业",
        "event_detail": "伤官见官，有跳槽、辞职或与上级冲突之象，需注意言行",
        "base_confidence": 0.83,
        "classical_source": "《子平真诠·论伤官》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "E10_bijie_bei_zhi": {
        "id": "E10",
        "category": "十神特殊",
        "interaction_type": "制",
        "target": "比劫",
        "trigger": "被官杀制",
        "event_type": "人际",
        "event_detail": "比劫被官杀所制，竞争中可能落于下风，但规则和秩序会约束不利因素",
        "base_confidence": 0.63,
        "classical_source": "《子平真诠》",
        "strength_coefficient": 0.70,
        "causality_directness": 0.65,
        "classical_authority": 0.65,
    },

    # ==========================================================
    # 类别 F：特殊事件（7条）
    # ==========================================================
    "F1_dayun_transition": {
        "id": "F1",
        "category": "特殊事件",
        "interaction_type": "换运",
        "target": "大运",
        "event_type": "综合",
        "event_detail": "该年为换大运之年，十年一变，人生进入新阶段，各方面可能有较大变化",
        "base_confidence": 0.85,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "F2_sanxing_quan": {
        "id": "F2",
        "category": "特殊事件",
        "interaction_type": "三刑全",
        "target": "全局",
        "event_type": "健康/官非",
        "event_detail": "三刑全见，需注意官非诉讼、意外伤害或身体病痛",
        "base_confidence": 0.67,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.65,
        "classical_authority": 0.60,
    },
    "F3_sanhe_formed": {
        "id": "F3",
        "category": "特殊事件",
        "interaction_type": "三合",
        "target": "全局",
        "event_type": "综合",
        "event_detail": "三合局形成，某五行力量剧增，该五行所代表的人事有重大发展",
        "base_confidence": 0.72,
        "classical_source": "《子平真诠·论用神变化》",
        "strength_coefficient": 0.85,
        "causality_directness": 0.70,
        "classical_authority": 0.75,
    },
    "F4_chongkai_muku": {
        "id": "F4",
        "category": "特殊事件",
        "interaction_type": "冲墓",
        "target": "墓库",
        "event_type": "财运",
        "event_detail": "冲开墓库，所藏之物得以释放，有财富、才华突然展现或获得的机会",
        "base_confidence": 0.63,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.60,
        "classical_authority": 0.60,
    },
    "F5_liunian_chong_dayun": {
        "id": "F5",
        "category": "特殊事件",
        "interaction_type": "天克地冲",
        "target": "大运",
        "event_type": "综合",
        "event_detail": "流年与大运天克地冲，十年运势在此年受到大的冲击，是十年中最重要的转折点",
        "base_confidence": 0.78,
        "classical_source": "《滴天髓》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.80,
        "classical_authority": 0.75,
    },
    "F6_both_yongshen": {
        "id": "F6",
        "category": "特殊事件",
        "interaction_type": "干支用神",
        "target": "全局",
        "event_type": "综合",
        "event_detail": "流年干支皆为用神，是难得的吉年，各方面运势极佳",
        "base_confidence": 0.78,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.85,
        "classical_authority": 0.75,
    },
    "F7_both_jishen": {
        "id": "F7",
        "category": "特殊事件",
        "interaction_type": "干支忌神",
        "target": "全局",
        "event_type": "综合",
        "event_detail": "流年干支皆为忌神，是需格外谨慎的一年，各方面压力较大",
        "base_confidence": 0.74,
        "classical_source": "《子平真诠·论行运》",
        "strength_coefficient": 0.90,
        "causality_directness": 0.80,
        "classical_authority": 0.70,
    },

    # ==========================================================
    # 类别 G：天干五合事件 + 官杀混杂 + 岁运并临 + 半合 + 泄秀（新增）
    # ==========================================================
    "G1_hequ_yongshen": {
        "id": "G1",
        "category": "天干五合",
        "interaction_type": "合去",
        "target": "用神",
        "event_type": "事业",
        "event_detail": "流年天干合用神，用神被绊住暂不得力，事业运势受牵制",
        "base_confidence": 0.77,
        "classical_source": "《子平真诠·论用神变化》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.80,
        "classical_authority": 0.80,
    },
    "G2_hequ_jishen": {
        "id": "G2",
        "category": "天干五合",
        "interaction_type": "合去",
        "target": "忌神",
        "event_type": "综合",
        "event_detail": "流年天干合忌神，不利因素被绊住解除，运势好转",
        "base_confidence": 0.72,
        "classical_source": "《子平真诠·论用神变化》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.80,
        "classical_authority": 0.70,
    },
    "G3_hehua_yongshen": {
        "id": "G3",
        "category": "天干五合",
        "interaction_type": "合化",
        "target": "用神",
        "event_type": "综合",
        "event_detail": "天干合化出用神五行，因合得利，运势由逆转顺",
        "base_confidence": 0.67,
        "classical_source": "《子平真诠·论十干配合性情》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.70,
        "classical_authority": 0.70,
    },
    "G4_hehua_jishen": {
        "id": "G4",
        "category": "天干五合",
        "interaction_type": "合化",
        "target": "忌神",
        "event_type": "综合",
        "event_detail": "天干合化出忌神五行，因合招祸，需谨慎行事",
        "base_confidence": 0.67,
        "classical_source": "《子平真诠·论十干配合性情》",
        "strength_coefficient": 0.75,
        "causality_directness": 0.70,
        "classical_authority": 0.70,
    },
    "G5_guansha_hunza_liunian": {
        "id": "G5",
        "category": "十神特殊",
        "interaction_type": "混杂",
        "target": "官杀",
        "event_type": "事业",
        "event_detail": "命局官杀混杂，流年更加重混杂之势，事业是非增多，方向迷茫",
        "base_confidence": 0.74,
        "classical_source": "《子平真诠·论正官》",
        "strength_coefficient": 0.80,
        "causality_directness": 0.75,
        "classical_authority": 0.80,
    },
    "G7_suiyun_binglin": {
        "id": "G7",
        "category": "特殊事件",
        "interaction_type": "岁运并临",
        "target": "全局",
        "event_type": "综合",
        "event_detail": "岁运并临，流年干支与大运干支完全相同，是这十年中最关键的年份，吉凶力量加倍",
        "base_confidence": 0.85,
        "classical_source": "《渊海子平》",
        "strength_coefficient": 1.0,
        "causality_directness": 0.85,
        "classical_authority": 0.85,
    },
    "A13_banhe": {
        "id": "A13",
        "category": "宫位互动",
        "interaction_type": "半合",
        "target": "全局",
        "event_type": "综合",
        "event_detail": "流年与命局形成半合局，某五行力量正在凝聚增强，相关领域有向好趋势",
        "base_confidence": 0.57,
        "classical_source": "《子平真诠·论用神变化》",
        "strength_coefficient": 0.65,
        "causality_directness": 0.60,
        "classical_authority": 0.55,
    },
    "E11_xie_xiu": {
        "id": "E11",
        "category": "日主互动",
        "interaction_type": "泄",
        "target": "日主",
        "event_type": "综合",
        "event_detail": "日主之气被流年引泄（食伤泄秀），身旺者才华展现，身弱者精力消耗需注意调节",
        "base_confidence": 0.60,
        "classical_source": "《子平真诠·论食神》",
        "strength_coefficient": 0.65,
        "causality_directness": 0.60,
        "classical_authority": 0.60,
    },
}

# 总规则数
assert len(EVENT_RULES) == 53, f"应有53条规则，实际{len(EVENT_RULES)}条"

# 类别计数验证
_cat_counts = {}
for r in EVENT_RULES.values():
    _cat_counts[r["category"]] = _cat_counts.get(r["category"], 0) + 1


# ============================================================
# 公共接口
# ============================================================

def get_rule(rule_id: str) -> dict:
    """获取单条规则"""
    return EVENT_RULES.get(rule_id, {})


def get_all_rules() -> dict:
    """获取全部规则"""
    return EVENT_RULES


def get_rules_by_category(category: str) -> list[dict]:
    """按类别获取规则"""
    return [r for r in EVENT_RULES.values() if r["category"] == category]


def compute_confidence(rule: dict) -> float:
    """三维合成置信度

    公式：典籍支撑 × 0.5 + 因果直接性 × 0.3 + 互动强度 × 0.2
    """
    return round(
        rule["classical_authority"] * 0.5
        + rule["causality_directness"] * 0.3
        + rule["strength_coefficient"] * 0.2,
        2,
    )
